### ISSUE TITLE
[BUG] (sort of)

### ISSUE THREAD

**Issue by 274188A** [fretje/heroplate#7]
just noticed this - would it be feasible to change to the recommended one?  Not tried myself , just going through your template to see if I can get it going.

![image](https://user-images.githubusercontent.com/40014477/223356518-876ac345-e60a-4a53-ab70-5cf53a242269.png)

**Comment by fretje** [comment]
I have updated the packages (https://github.com/fretje/heroplate/commit/3690e9b5a68d761db7db93ec837142a213af734b).

So this should be fixed now.

**Comment by 274188A** [comment]
Cheers
